version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      # Use the Windows-compatible PowerShell command to get ECR login details
      - echo $(aws ecr get-login-password --region ap-south-1) | docker login --username AWS --password-stdin 011528285140.dkr.ecr.ap-south-1.amazonaws.com
      - echo Setting repository URI
      - set REPOSITORY_URI=011528285140.dkr.ecr.ap-south-1.amazonaws.com/spring-demo-ecr
      - echo Setting image tag
      - set IMAGE_TAG=build-%CODEBUILD_BUILD_ID:~12%
  build:
    commands:
      - echo Build started on %date%
      - echo Building the Jar file
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t %REPOSITORY_URI%:latest .
      - docker tag %REPOSITORY_URI%:latest %REPOSITORY_URI%:%IMAGE_TAG%
  post_build:
    commands:
      - echo Build completed on %date%
      - echo Pushing to repo
      - docker push %REPOSITORY_URI%:latest
      - docker push %REPOSITORY_URI%:%IMAGE_TAG%
      - echo Writing image definitions file...
      # Define your container name
      - set DOCKER_CONTAINER_NAME=spring-demo-ecr-container
      - echo [{"name":"%DOCKER_CONTAINER_NAME%","imageUri":"%REPOSITORY_URI%:%IMAGE_TAG%"}] > imagedefinitions.json
      - echo %DOCKER_CONTAINER_NAME%
      - echo Printing imagedefinitions.json
      - type imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/springboot-aws-deploy.jar
